CRYSTAL_VERSION=1.0
CRYSTAL_REGULAR_VERSION_NAME=Amethyst
CRYSTAL_CLEAR_VERSION_NAME=Amber
CRYSTAL_BUILD_TYPE?=ARGENT
CRYSTAL_MAINTAINER?=NOBODY
CRYSTAL_PURITY?=VANILLA
CRYSTAL_CUSTOM_TYPE?=REGULAR

CRYSTAL_DATE_YEAR := $(shell date -u +%Y)
CRYSTAL_DATE_MONTH := $(shell date -u +%m)
CRYSTAL_DATE_DAY := $(shell date -u +%d)

CRYSTAL_BUILD_DATE := $(CRYSTAL_DATE_YEAR).$(CRYSTAL_DATE_MONTH).$(CRYSTAL_DATE_DAY)

ifeq ($(CRYSTAL_CUSTOM_TYPE),CRYSTALCLEAR)
    CRYSTAL_DISPLAY_VERSION=$(CRYSTAL_VERSION)-$(CRYSTAL_CLEAR_VERSION_NAME)
    CRYSTAL_VERSION_NAME=$(CRYSTAL_CLEAR_VERSION_NAME)
else
    CRYSTAL_DISPLAY_VERSION=$(CRYSTAL_VERSION)-$(CRYSTAL_REGULAR_VERSION_NAME)
    CRYSTAL_VERSION_NAME=$(CRYSTAL_REGULAR_VERSION_NAME)
endif